name: Build & Publish Release APK
run-name: Building apk with version ${{github.ref_name}}

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: specify java version
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: make Gradle executable
        run: chmod +x ./gradlew
      - name: build Release APK
        run: ./gradlew assembleRelease
      - name: create github release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: /home/runner/work/check-mate/check-mate/app/build/outputs/apk/release/app-release.apk
