name: Build & Publish Release APK
run-name: Building apk with version ${{github.ref_name}}

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
      - name: decode keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          filename: 'keystore/your_signing_keystore.jks'
          encodedString: ${{ secrets.KEYSTORE }}
      - name: checkout code
        uses: actions/checkout@v4
      - name: specify java version
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: make Gradle executable
        run: chmod +x ./gradlew
      - name: build Release APK
        run: ./gradlew app:bundleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      - name: find apk
        run: find /home/runner -iname '*.apk' 2>/dev/null
      - name: create github release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: /home/runner/work/check-mate/check-mate/app/build/outputs/apk/release/app-release.apk
